# NumPy Basics
---
Today, we will learn about the NumPy library, which is the core library for numerical computing in Python and is used in many other packages. 

If you want to get anywhere with **Pandas** or **Scikit-Learn** (which will be your bread and butter if you get into data science!), you need a working grasp of **NumPy** first. Both libraries are built on top of NumPy arrays: Pandas extends them with labels and tabular operations, while Scikit-Learn consumes them for every model you’ll train. Without understanding NumPy’s basics—like how arrays store data, how shapes and reshapes work, and how vectorized operations replace loops—you'll constantly run into mysterious errors ("expected 2D array, got 1D array") and treat these libraries like black boxes. Mastering NumPy gives you the foundation to actually control your data, debug problems faster, and understand what's happening under the hood. In short: **NumPy is the grammar, pandas and scikit-learn are the sentences.**

We have mentioned in the previous sessions that Python is slow compared to other languages. Luckily, NumPy leverages some fast languages such as C and Fortran under the hood, allowing us to avoid the headaches of low-level programming while still enjoying their efficiency.

## Arrays: Introduction
---
NumPy's main data structure is the *array*, a so-called `np.ndarray` to be precise, which is a generic n-dimensional array that can hold elements of the same type. Think of an ndarray simply as a "container" for your data; it has attributes like `.shape`, `.ndim`— which you will get to know in this notebook. Put differently, an ndarray is the data structure NumPy gives us to store numbers efficiently.


Last week, we have seen that lists in Python are not really suited for numerical computing and that they don't provide an interface for linear algebra operations. But linear algebra is one of the main building blocks of machine learning!

For instance, we discussed that given a list `x = [1, 2, 3]`, we would like multiplication to act element-wise such as with scalar products in linear algebra, i.e., we would like to obtain `x * 2 == [2, 4, 6]` instead of `x * 2 == [1, 2, 3, 1, 2, 3]` as is the default behavior for lists. The same goes for vector addition.

In [1]:
# In an ideal world, we would like to obtain [2, 4, 6]
x = [1, 2, 3]
x * 2

[1, 2, 3, 1, 2, 3]

In [2]:
# Similarly, we would now like to obtain [5, 7, 9]
y = [4, 5, 6]
x + y

[1, 2, 3, 4, 5, 6]

Luckily for us, NumPy provides all these functionalities and moving from a list to an array is as easy as calling a function. Let's have a look.

In [3]:
# First, we import NumPy under the alias np, this is the standard way of importing NumPy.
import numpy as np

In [4]:
# We now cast these lists to NumPy array and observe the difference.
x = np.array(x) # Equivalent to x = np.array([1, 2, 3])
x * 2
display(x, x * 2)

y = np.array(y)
x + y

display(y, x + y)

array([1, 2, 3])

array([2, 4, 6])

array([4, 5, 6])

array([5, 7, 9])

We have used the term "cast" in the previous comment. In Python, "casting" means converting an object of some type into another type. (That's not 100 percent precise language, but good enough for data scientists working with Python :-)

Note also the use of `display()`. By default, only the last object calculated in a code cell is shown as output. If you want to see more objects, you can use `dislay()` as we have done here.

In [5]:
# Of course, we can still access single elements like we did with lists.
x[0], x[2]

(1, 3)

The last cell shows you another option for seeing multiple results. In `x[0], x[2]`, we just separated the two objects by a comma. Python creates a tuple and displays it. If you have a little bigger objects, the `display()` option is usually preferred. (And often, the nicest option is `print(f"[...]")`, but it also requires the most typing.)

Et voilà&hellip; using NumPy, we can now do some linear algebra with our programming language. Beautiful! 🤩

#### 🤔 Notice a few things:
- When we call `np.array`, we call the `array()` function from the `numpy` package (which we imported under the alias `np`). Recall from the previous sessions that this is how Python packages (or their sub-modules) work: you import them and then access their functions/attributes.
- The output is not only different with respect to the values, but also with respect to the type of object. We don't have `[2, 4, 6]` which would be a list, but rather `array([2, 4, 6])` telling us that we are dealing with an array.
- Note that the single elements now have a special integer type, which is different from the default `int` type in Python. It's an `np.int64` type which is a 64-bit integer. We can ignore this detail for now but it is good to keep this difference in mind.
- In linear algebra terms, we did scalar multiplication and vector addition but be careful in thinking too much of linear algebra in the context of NumPy, let us look at some more examples&hellip;


In [6]:
# The modulo operation is not defined on vector spaces, but works fine in NumPy 
display(x)
x % 3

array([1, 2, 3])

array([1, 2, 0])

In [7]:
# The same holds for the power operation
display(x)
x ** 2

array([1, 2, 3])

array([1, 4, 9])

In [8]:
# Multiplying two arrays gives us an element-wise multiplication
print(f"x: {x}")
print(f"y: {y}")
x * y

x: [1 2 3]
y: [4 5 6]


array([ 4, 10, 18])

If we were pure mathematicians, we might be somewhat annoyed or confused by the above behavior. Luckily, we are data scientists and this behavior is going to be very useful to us.

NumPy doesn't only provide us with a convenient data structure for numerical computing, but it also comes with a flurry of useful mathematical functions. Once again, note that these are not defined on vector spaces, but will be applied element-wise if we apply them to NumPy arrays.

In [9]:
# We can take the sine of every element
np.sin(x)


array([0.84147098, 0.90929743, 0.14112001])

In [10]:
# ... or we can take the exponential of every element
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [11]:
# ... and of course, we can also chain these operations
np.exp(np.sin(x))

array([2.31977682, 2.48257773, 1.15156284])

So far so good, but we are still missing something. In particular, we are missing the ability to do truly do linear algebra. For instance, if we think about the vector multiplication `x * y` we have done before, we would also like to be able to do vector multiplication in the linear algebra sense, i.e., let $$x = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}, \qquad y = \begin{bmatrix} 4 \\ 5 \\ 6 \end{bmatrix}$$ we would like to be able to do something such as $$x^\top y = 1 \cdot 4 + 2 \cdot 5 + 3 \cdot 6 = 32$$ or $$x y^\top = \begin{bmatrix} 1 \cdot 4 & 1 \cdot 5 & 1 \cdot 6 \\ 2 \cdot 4 & 2 \cdot 5 & 2 \cdot 6 \\ 3 \cdot 4 & 3 \cdot 5 & 3 \cdot 6 \end{bmatrix} = \begin{bmatrix} 4 & 5 & 6 \\ 8 & 10 & 12 \\ 12 & 15 & 18 \end{bmatrix}.$$

But before we do this, we must first understand the *shapes* and *dimensions* of our arrays.

## Arrays: Shapes and reshapes
---

In [12]:
# NumPy arrays have a `shape` attribute, which tells us the number of elements per dimension.
x.shape

(3,)

OK, that means that x has 3 elements along a first dimension; and there are no further dimension. We infer that there are no further dimensions since there is nothing after the comma. Maybe you are confused by the format of this funny output `(3,)`. What this means is that `x.shape` has type tuple: 

In [13]:
type(x.shape)

tuple

A **tuple** is an ordered collection of items in Python, similar to a list, but with two key differences:

- Tuples are written with parentheses `()` instead of square brackets `[]`.
- Tuples are **immutable** → once created, you cannot change their contents.

A shape describes a property of an array — its structure. That shouldn’t change accidentally, so NumPy uses a tuple (immutable) to signal: "this is descriptive info, not something you’re supposed to edit."

OK, back to the vector `x`. It's shape is 3, as we just learned. You may ask yourself whether the 3 elements of the vector build a row or a column vector. The answer is: so far, the factor is just "flat". It does not know whether it has column or row format, it just contains three elements. And it has only one dimension. More on this in a second.

In [14]:
# We can also access the dimensionality directly. This confirms that x has only one dimension.
x.ndim

1

So `x` has 3 elements in its first dimension, and it is a 1-dimensional array. Keep in mind: `.shape` does not tell us the number of elements in the array but the number of elements per dimension.

Now we get to the tools to make vectors "aware" of whether they are column or row vectors. The tool for this is the reshape function/method.

The intuitive way to create a vector with 3 rows (thus a column vector) is this:

In [15]:
# Reshape x such that it has 3 elements in its first dimension 
# and 1 element in its second dimension
x.reshape(3,1)

array([[1],
       [2],
       [3]])

It requires the eye to get used to this output format with so many brackets. But that's how it is.

More commonly, you will see experienced data scientsts using this:

In [16]:
# This is how experienced programmers create a column vector:
xr = x.reshape(-1, 1)
yr = y.reshape(-1, 1)

display(xr)
display(yr)

array([[1],
       [2],
       [3]])

array([[4],
       [5],
       [6]])

The `-1` value of the first argument may look a bit weird to you. Read `reshape(-1, 1)` like this: Form a vector (or matrix) with one column (the `1` in the second argument), and create as many rows as a necessary for this (the `-1` in the first argument).

#### ➡️ ✏️ Your turn
In the cell below, convert x and y to row vectors. Make sure that both outputs are visible.

In [17]:
#  ➡️ Write your code here ...

In [18]:
# SOLUTION
# Let's look at the reshaped arrays
display(
    x.reshape(1,-1)
    )

display(
    y.reshape(1,-1)
    )

array([[1, 2, 3]])

array([[4, 5, 6]])

Let's go back to the column vector `xr`. We now see that we don't have `array([1, 2, 3])` but rather `array([[1], [2], [3]])`, i.e., our arrays are now 2-dimensional. Let's verify this.

In [19]:
# We expect the dimensionality to be 2
xr.ndim

2

In [20]:
# We expect the shape to be (3, 1)
xr.shape

(3, 1)

Alright, so we have our 2-dimensional arrays, can we now do our matrix multiplication?

In [21]:
display(xr, yr)
xr * yr

array([[1],
       [2],
       [3]])

array([[4],
       [5],
       [6]])

array([[ 4],
       [10],
       [18]])

&hellip; nope, this is still an element-wise multiplication, with the difference that the resulting array is 2-dimensional. So how do we do matrix multiplication in NumPy?

We can use the `@` operator or the `dot` method to perform matrix multiplication.

In [22]:
xr @ yr

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

&hellip; oh no! It seems like we have a problem. Did I lie to you?

No, it's simply that we have to be careful with the shapes of the arrays we are multiplying. In particular, we have to make sure that the number of columns in the first array matches the number of rows in the second array. This is linear algebra 101, we cannot just multiply arbitrary matrices / vectors. In the jargon, we say that the matrices need to be "conforming". In this case, we need the transpose of `yr` (or `xr`) to perform the matrix multiplication. Once again, this is easily done in NumPy.

In [23]:
# Transpose xr, this gives us a (1, 3) x (3, 1) -> (1, 1) multiplication
xr.T @ yr

array([[32]])

In [24]:
# ... or we can also transpose yr to obtain a (3, 1) x (1, 3) -> (3, 3) multiplication
xr @ yr.T

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

So, finally, we are able to do proper matrix algebra! If we were to look at the shapes and dimensions of the arrays, we would see that they have shape (1, 1) and (3, 3) respectively, both with two dimensions. Now, let's quickly look at indexing multidimensional arrays.

In [25]:
# Store the 3x3 matrix above in the variable mat
mat = xr @ yr.T
# Check that the shape is (3, 3) and the dimensionality is 2
print("Shape is", mat.shape, "and the dimensionality is", mat.ndim)

Shape is (3, 3) and the dimensionality is 2


In [26]:
# What happens when we try to index a single element?
mat[0]

array([4, 5, 6])

We have now returned an entire row of the matrix. This is not only the 0th element of the matrix but rather the first element of the first dimension!

In [27]:
# We can also index a single element, say the 0th row and 1st column
mat[0, 1] # mat[0][1] would also work, but is less elegant and more error-prone

5

**Note: the dimensions of a matrix are always indicated in the order "row, column"!** You need to know this when weaking up at night within 3 seconds!

NumPy also provides ways to create arrays without having to manually enter the lists, however, not any type of array can be create this way. Here are a few useful ones.

In [ ]:
# Create a 1-dimensional array with 10 elements all equal to 1
np.ones(10)

In [ ]:
# We can also create arrays of zeros
np.zeros(10)

In [ ]:
# ... and often more useful, a range of increasing numbers from 0 to n-1
np.arange(10)

In [ ]:
# Or create a 1-dimensional array of linearly spaced numbers between 0 and 5
np.linspace(0, 5, 10) # (start, end, number of elements)

In [ ]:
# np.zeros and np.ones also allow us to create multidimensional arrays
np.zeros((3, 3))

In [ ]:
# Finally, the identity matrix is often useful and can be created with
np.eye(5) # 5x5 identity matrix

Keep in mind that using `np.arange` and `np.linspace`, we can only create 1-dimensional arrays. However, given what we have learned so far, we know that we can easily reshape them to create multidimensional arrays!

⚠️ Be careful when reshaping arrays, make sure you understand which elements are passed to which dimension!

In [ ]:
# Create a 2x5 array of integers from 0 to 9
# Note how the elements are filled row-wise!
np.arange(10).reshape(2, 5)

#### ➡️ ✏️ Your turn
How can we create a 5x2 array of integers from 0 to 9 where the elements are filled column-wise? I.e. the fist column contains the numbers 0, 1, ..., 4, and the second column contains the numbers from 5 to 9. You are not allowed to manipulate anything "manually"! 

NumPy doesn't provide direct support for this, but we can use some tricks to achieve this&hellip; Any ideas?

*Hint*: The solution takes a short line. But be prepared for some mental gymnastics :-)

In [ ]:
# ➡️ ... code to follow once discussed, try it out yourself!


In [28]:
# SOLUTION
# There are probably many ways. Here, you see two possible ones

# Here is a solution that works, where you do not need the 5
np.arange(10).reshape(1,-1).reshape(2,-1).T

# And here is a solution that is shorter and more elegant
np.arange(10).reshape(2,5).T

# It may require some mental gymnastics if you are not used to the world of shapes, reshapes, rows, and columns...

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

## Broadcasting
---
Okay, one final thing to understand before you start working on an exercise by yourself. NumPy also supports addition and subtraction of arrays, **even when these have different shapes**! Now, of course, the shapes have to be somehow compatible. Let's look at an example.

In [29]:
# Recall, xr is (3, 1) and mat is (3, 3). What happens when we add them?
display(xr, mat)
mat + xr

array([[1],
       [2],
       [3]])

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

array([[ 5,  6,  7],
       [10, 12, 14],
       [15, 18, 21]])

The addition is applied element-wise again, i.e., the first element of `x` is added to the first **row** of the matrix `mat`, the second element is added to the second row, and so on. This behavior is logical since `xr` is a column vector.

If we instead want to add the first element of `x` to the first **column** of `mat`, we can do so by reshaping `x` to be `(1, 3)` instead of `(3, 1)`. 

In [ ]:
mat + xr.T

In [ ]:
# Of course, multiplication exhibits the same behavior
display(xr, mat)
mat * xr

This behavior is also called **broadcasting**. It takes a while to get used to this behavior, but it is a very powerful feature of NumPy **that you will be using all the time**, either explicitly, or implicitly because Pandas uses it all the time. If you don't understand broadcasting, Pandas will happily stretch arrays in ways you didn't expect—so instead of getting the analysis you wanted, you'll get wrong numbers that *look* correct and won't raise an error. But they can be very wrong indeed! Why worry about Pandas, this is a notebook on NumPy, after all? Well, let's remember that Pandas is built on top of NumPy, and it's bread and butter for data scientists.

🙀 🤯 [The official NumPy documentation on broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html) is much more detailed than this notebook and provides a few examples with illustrations. It is also somewhat more involved, but if you have some spare time, it is great resource to look at.

⚠️ One last word of caution before we end this section: broadcasting only works when the shapes are compatible. But more importantly, **you might sometimes believe that broadcasting is applied in a certain dimension, while it is applied in another dimension**. This is a common source of bugs and mistakes. Make sure you understand the shape of your arrays and how broadcasting works before using it blindly.

In [30]:
# An example where broadcasting fails, a 2-dimensional array and a 3x3 matrix
z = np.array([1, 2])
display(z, mat)
mat + z

array([1, 2])

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

#### ➡️ ✏️ Your turn
You have recently created your own artisanal startup (selling, e.g. artisanal chocolate/truffles) and, as a good data scientist, you want to quantitatively understand how your business is doing. You have the following data at hand:
- `daily_quantities_sold`: a $3\times 4$ matrix containing the *daily* quantities sold for 4 different items (the columns) for 3 different locations (the rows).
- `prices`: a 4-dimensional vector (1-dimensional array with 4 elements) containing the prices for the 4 items. Note that prices are identical across locations.
- `unit_costs`: a $3\times 4$ matrix containing the variable unit costs for the 3 locations (local salaries may differ).


You have the following tasks:
1. Compute the daily total revenue for each location (i.e. not the revenue per item, but overall). *Hint*: A single matrix multiplication will do the trick.
2. Due to different holiday arrangements, the first location was open for 28 days, the second for 30 days, and the third for 27 days during the first month of operation. Compute a matrix that contains revenues per item per location for the entire first month. Rows correspond to locations, columns to items.
3. Calculate monthly costs per item and location. Rows correspond again to locations, columns to items.
4. Which was the most profitable location/item combination? (E.g., the third item sold in the second location). Now that you have some insights on your business, what changes would you make to your current strategy?

*HINT:* You find most of the matrices that you need to start the calculations in the next code cell below.

In [31]:
quantities_daily = np.array([
    [100, 125, 130, 200],
    [300, 200, 150, 200],
    [500, 50, 300, 125]
])

# E.g., the first item was sold 500 times in the third location 
# and the third item was sold 150 times in the second location

prices = np.array([30, 80, 50, 40])
# First item is sold at $30, second $80, third $50, fourth $40

unit_costs = np.array([
    [20, 78, 10, 30],
    [19, 81, 12, 32],
    [22, 75, 10, 28]
])

In [ ]:
# ➡️ ✏️ your code here...


In [32]:
# SOLUTION
# Problem 1
print("PROBLEM 1")
# We get the revenues per location if we multiply each row of sales (containing 4 products) with the price vector. For this, the price needs to have dimension 4 by 1.
# Let's investigate the initial dimensions of sales and prices

print(f"quantities has shape {quantities_daily.shape}  \nprices has shape {prices.shape}\n")#

# So the price is still "flat" (unidimensional). To get daily revenues, we use
revenues_daily_per_location = quantities_daily@prices.reshape(-1,1)

# Display the result
print(f"Daily revenues per location:\n{revenues_daily_per_location}\n")

print("-"*50)

# Problem 2
print("PROBLEM 2")
# To get revenues per item per location, we need to multiply the numbers for each location with the respective number of opening days.
#  So we first have to create a vector for open days
days = np.array([28,30,27])
print(f"days:\n{days}\n")

# For total quantities sold per item per location, we first need to multiply the first row of quantities (location 1) with the first element of days, the second row of quantities
# with the second element of days etc. This is now a perfect application of broadcasting. 
# We then also need to multiply each item with the respective price.

# Get monthly quantities
quantities_monthly = quantities_daily*days.reshape(-1,1)
# Note that we multiply each row with the same number, as days are per location, and rows correspond to locations.
print(f"monthly quantities:\n{quantities_monthly}\n")

# Now we need to multiply each item quantity with the respective price. For this, we need to multiply each column with the same price
revenues_monthly = quantities_monthly*prices.reshape(1,-1)
print(f"monthly revenues:\n{revenues_monthly}\n")

print("-"*50)

# Problem 3
print("PROBLEM 3")
# To get total monthly costs, we need to multiply monthly quantities with their unit costs.
# This requires element-wise multiplication rather than matrix multiplication
costs_monthly = quantities_monthly*unit_costs
print(f"monthly costs:\n{costs_monthly}\n")

print("-"*50)

# Problem 4
print("PROBLEM 4")
# We now calculate revenues minus costs
profits = revenues_monthly - costs_monthly
print(f"Profits per item/location are:\n{profits}\n")

print(f"The maximum element of profits is {profits.max()}.\n")

# If you want to get the indices of the maximum:
row, col = np.unravel_index(profits.argmax(), profits.shape)
print(f"The maximum value of {profits[row, col]} occurs at position ({row}, {col})")
# That is admittedly not very elegant, but it is as good as numpy allows us to do this.

# It is thus item 3 in location 3.






PROBLEM 1
quantities has shape (3, 4)  
prices has shape (4,)

Daily revenues per location:
[[27500]
 [40500]
 [39000]]

--------------------------------------------------
PROBLEM 2
days:
[28 30 27]

monthly quantities:
[[ 2800  3500  3640  5600]
 [ 9000  6000  4500  6000]
 [13500  1350  8100  3375]]

monthly revenues:
[[ 84000 280000 182000 224000]
 [270000 480000 225000 240000]
 [405000 108000 405000 135000]]

--------------------------------------------------
PROBLEM 3
monthly costs:
[[ 56000 273000  36400 168000]
 [171000 486000  54000 192000]
 [297000 101250  81000  94500]]

--------------------------------------------------
PROBLEM 4
Profits per item/location are:
[[ 28000   7000 145600  56000]
 [ 99000  -6000 171000  48000]
 [108000   6750 324000  40500]]

The maximum element of profits is 324000.

The maximum value of 324000 occurs at position (2, 2)


## Reduction/Summary Functions
---

We already have a quite powerful toolset to work with arrays and do linear algebra numerically. However, thinking in terms of matrices and vectors is sometimes cumbersome. For instance, thinking about matrix multiplication to compute the revenue of your business is not always intuitive. It is correct, but sometimes we like to think in different terms. For instance, we may know that we have to multiply each item by its price and then sum it up by location, but it may not be as easy to see how this looks like in matrix form.

This is where the so-called *reduction* functions come into play. Reduction functions are functions that reduce the dimensionality of an array by applying a function to the elements of the array. For instance, the sum of all elements in an array is a reduction function. While *reduction functions* is NumPy lingo, data scientists would often refer to them as *summary functions*.

E.g., suppose we wanted to know how many items we sold in total per location. We could in theory do a matrix multiplication with a vector of ones, but this is not very clear.

In [33]:
# Correct but cumbersome:
display(
    quantities_daily@np.ones(4).reshape(4,1)
    )

# Total number of items sold per location the reduction function way
display(
    np.sum(quantities_daily, axis=1)
)

array([[555.],
       [850.],
       [975.]])

array([555, 850, 975])

We must mention a few things:
- The first version gives us a $3\times 1$ matrix, as is expected from matrix multiplication.
- The second version gives us a 1-dimensional array with 3 elements, we have *reduced* the dimensionality by summing over the appropriate axis.
- We passed the keyword `axis=1` to the `sum` function, which tells us that we want to sum over the first dimension. (Be careful, in Python arrays start at the 0th dimension! So this means summing over columns. Recall the mantra: first rows, then columns.)

Let's look at some more examples of how reduction work.

In [ ]:
# If we wanted to know the total number of times each item was sold (summing over regions rather than items)
# we can sum over the 0th axis, resulting in a 1-dimensional array with 4 elements
np.sum(quantities_daily, axis=0)

In [ ]:
# Sometimes, we want to compute a reduction function without reducing the dimensionality.
# This can be achieved by passing `keepdims=True` to the function.
np.sum(quantities_daily, axis=1, keepdims=True)

In [ ]:
# If we don't pass the `axis` keyword, the function will reduce the entire array
# to a scalar, i.e., the total number of items sold
np.sum(quantities_daily)

Of course, we can also compute other reduction functions, such as the mean, the variance, the standard deviation, and so on.

In [ ]:
# Average number of items over all locations (per item type)
np.mean(quantities_daily, axis=0) 

In [ ]:
# Average number of items sold per location (over all item types)
np.mean(quantities_daily, axis=1)

In [ ]:
# Standard deviation of the number of items sold (over location)
np.std(quantities_daily, axis=0)

As you get comfortable with NumPy, you will find that you will use reduction functions more and more, as they allow for a very concise and expressive way to compute summary statistics. Moreover, they are prevalent in all other data science packages we will be using later on. We will seldom fall back to using explicit loops or matrix multiplications for this purpose. Reduction functions are just too convenient.

In fact, they are so prevalent that NumPy also allows to apply reduction functions as a *method of the array object*. This behavior will also come up in future packages, such as Pandas that we will cover next week.

In [ ]:
# Using sum as a method of the array object
quantities_daily.sum(axis=1)

In [ ]:
# Same goes for mean, std, etc.
quantities_daily.mean(axis=1)

## Filtering / Masking
---

Filtering is another important tool in data science. Since we will be dealing with *real world data*, we will often want to filter out or modify certain observations from our data in a programmatic way.

For instance, we may have a dataset of customer ratings of our products. We know that the ratings are on a scale from 1 to 10, but somehow our data is corrupted and contain some values that are not in this range.

In [34]:
# The array containing our customer ratings
ratings = np.array([-3,2,2,6,7,5,8,7,1,7,4,-4,8,7,7,1,7,4,4,6,5,9,9,1,10,1,4,1,4,6,5,9,5,-3,-5,3,-6,2,8,-7,1,6,3,9,5,-4,3,9,2])
ratings

array([-3,  2,  2,  6,  7,  5,  8,  7,  1,  7,  4, -4,  8,  7,  7,  1,  7,
        4,  4,  6,  5,  9,  9,  1, 10,  1,  4,  1,  4,  6,  5,  9,  5, -3,
       -5,  3, -6,  2,  8, -7,  1,  6,  3,  9,  5, -4,  3,  9,  2])

We quickly see that some numbers are negative. It's a small enough dataset that we can manually remove them, but this is not a scalable solution, which is what we will require for our projects.

Instead of looking at the numbers, we can try to see how many numbers are negative.

In [35]:
# Apply element-wise comparison and check how many numbers are negative
negative_ratings = ratings < 0

# Use f-strings to format the output nicely
print(f"There are {negative_ratings.sum()} negative ratings in the dataset")


print(f"The negative ratings make up {negative_ratings.mean():.2%}, of the total ratings")
# Notice that we can use the {:.2%} formatting to make the print output look nicer. This is a float formatting that shows the 
# number as a percentage with 2 digits after the decimal point.
# Try how ugly it looks without this formatting.

There are 7 negative ratings in the dataset
The negative ratings make up 14.29%, of the total ratings


Now, what to do with these negative ratings unfortunately always depends on the application and the data collection process. Many situations could be possible, e.g.,

1. The negative ratings are a mistake and should be removed.
2. The negative ratings are actually positive, there is just a mistake in the data collection process that added a minus sign.
3. The negative ratings have happened because in the data collection process, the maximum rating (10) was subtracted from the rating, mistakenly resulting in a negative number.
4. The negative ratings are actually the lowest possible rating, which is 1.

Many other situations are possible and we will have to think about what makes sense in our application. However, let's consider how to tackle each of these problems.

First, suppose we needed to remove the negative ratings. In this case, we can use boolean indexing to mask out the negative ratings, the idea is that `negative_ratings` contains booleans that are true for all negative ratings and false otherwise. Since this boolean array has the same shape as `ratings`, we can simply use it to index into `ratings` and only keep the positive ratings.

In [36]:
# The tilde sign negates the boolean array, i.e., true becomes false and vice versa
true_ratings = ratings[~negative_ratings]
true_ratings

array([ 2,  2,  6,  7,  5,  8,  7,  1,  7,  4,  8,  7,  7,  1,  7,  4,  4,
        6,  5,  9,  9,  1, 10,  1,  4,  1,  4,  6,  5,  9,  5,  3,  2,  8,
        1,  6,  3,  9,  5,  3,  9,  2])

In [ ]:
# Keep in mind that this array is now shorter than the original array!
ratings.shape, true_ratings.shape

Second, suppose that the negative ratings are actually positive, but there is just a mistake in the data collection. This case is actually quite trivial and we can simply use the absolute value of the ratings to correct for the mistake.

In [ ]:
true_ratings = np.abs(ratings)
true_ratings

Now, for the third case, things are started to get complicated. Given what we have learned in the last lecture, we might think of doing a loop that does something like this:

```python
# Notice that .size gives us the total number of elements in the array
for i in range(ratings.size):
    # If the rating is negative, we add 10 to it
    if ratings[i] < 0:
        ratings[i] += 10
```

This works, but it is not very efficient. If possible, we would like to avoid loops in NumPy and, instead, leverage the powerful broadcasting and vectorized operations that NumPy provides. Luckily, we can solve this problem using a nifty function called `np.where`.

You can think of `np.where` as *vectorized if-else statement*, e.g., `np.where(condition, value_if_true, value_if_false)`. Let's look at it in action.


In [ ]:
# If rating is negative, return rating + 10, otherwise return rating
true_ratings = np.where(ratings < 0, ratings + 10, ratings)
true_ratings

Finally, we can also use `np.where(ratings < 0, 1, ratings)` to solve the fourth case, it will work perfectly fine&hellip; but it would prevent us from learning something new! There is a more elegant solution for this case.

So here comes the function `np.clip`, which will simply clip the values of the array to a given range. All the initial values that fall inside the range are left unchanged. And the others are set to the corresponding clipping values, depending on whether they are below the range or above. 

In [37]:
# Clip the ratings to the range [1, 10]
true_ratings = np.clip(ratings, 1, 10)
true_ratings

array([ 1,  2,  2,  6,  7,  5,  8,  7,  1,  7,  4,  1,  8,  7,  7,  1,  7,
        4,  4,  6,  5,  9,  9,  1, 10,  1,  4,  1,  4,  6,  5,  9,  5,  1,
        1,  3,  1,  2,  8,  1,  1,  6,  3,  9,  5,  1,  3,  9,  2])

Phew&hellip; that's a lot to digest! But worry not, repetition is the key to mastering these topics. Make sure to play around with the code, try things out, and perhaps even apply some of these ideas in other undertakings linked to your own personal hobbies or interests!

So let's try solving an exercise to consolidate our understanding so far...

#### ➡️ ✏️ Your turn

You are the teaching assistant of a course on data science and would like to get some insights on the performance of your students.

You have the following data at hand:
- `exam_grades`: a 1-dimensional array containing the end-of-semester exam grades of 60 students.
- `midterm_grades`: a 1-dimensional array containing the midterm grades of the students,
- `attendance`: a 1-dimensional array containing the attendance of the students, i.e., percentage of classes attended (between 0 and 1, e.g., 0.9 for 90% attendance).

Your task is the following:
1. Compute the final grade for each student, where the final grade is the average of the exam and midterm grades, weighted by 70% and 30%, respectively.
2. What is the average final grade for all students? What is the standard deviation?
3. What is the percentage of students that have attended less than 70% of the classes?
4. What is the average final grade for students with 90% or more attendance?
5. What is the average final grade for students with less than 70% attendance?

In [38]:
# The data: exam grades, midterm grades, and attendance
exam_grades = np.array([3,4.5,4,6,5.5,6,5,4.5,5,5,6,3.5,6,3.5,3.5,4.5,5,4,5,4.5,3.5,4,3,3.5,5,4.5,5,5,4,3.5,4,4.5,5,4.5,4.5,4.5,6,4,6,4.5,5,5,5.5,6,5,5,5,5,5,4.5,5,4.5,5.5,5,6,5.5,4,5.5,5,3.5])
midterm_grades = np.array([6,4,4.5,5,3.5,4,5.5,5,4.5,4,5,4.5,5.5,3,5.5,6,5.5,3.5,5,5.5,4,4.5,3,5,6,5,4,3.5,4.5,6,4.5,3,5.5,4,5,4.5,5.5,3,6,4.5,5,5.5,4,5,5,4.5,6,4,4.5,6,4,6,3,4,5,3.5,4,5,5,5])
attendance = np.array([.8,.5,.9,.8,1,.9,.8,.9,.8,.5,.9,.9,.7,.7,.6,1,.8,.6,.9,.9,.9,.6,.9,.9,.7,.9,.7,.9,1,.9,.6,.9,.9,.9,.9,.9,.7,.9,1,.9,.9,.7,.9,.7,.7,.9,.9,.5,.9,1,.7,.7,.7,.8,.9,1,.5,.7,.8,.5])

In [ ]:
# ➡️ ✏️ your code here...
# Feel free to create as many new cells as needed

In [55]:
# SOLUTION
# Problem 1
print("PROBLEM 1")

final_grades = 0.7*exam_grades + 0.3*midterm_grades

display(final_grades)
print("-"*100)

# Problem 2
print("PROBLEM 2")
print(f"The mean final grade is {        final_grades.mean()        :.2f}. The standard deviation is {       final_grades.std()     :.2f}.")
print("-"*100)

# Problem 3
print("PROBLEM 3")
print(f"The percentage of students attenting less than 70% of classes is {     (attendance<0.7).mean()*100    :.1f}%.")
print("-"*100)

# Problem 4
print("PROBLEM 4")
print(f"The average grade of those who attended at least 90% is {    final_grades[attendance>=.9].mean()    :.2f}.")
print("-"*100)

# Problem 5
print("PROBLEM 5")
print(f"The average grade of those who attended less than 70% is {    final_grades[attendance<.7].mean()    :.2f}.")
print("-"*100)

PROBLEM 1


array([3.9 , 4.35, 4.15, 5.7 , 4.9 , 5.4 , 5.15, 4.65, 4.85, 4.7 , 5.7 ,
       3.8 , 5.85, 3.35, 4.1 , 4.95, 5.15, 3.85, 5.  , 4.8 , 3.65, 4.15,
       3.  , 3.95, 5.3 , 4.65, 4.7 , 4.55, 4.15, 4.25, 4.15, 4.05, 5.15,
       4.35, 4.65, 4.5 , 5.85, 3.7 , 6.  , 4.5 , 5.  , 5.15, 5.05, 5.7 ,
       5.  , 4.85, 5.3 , 4.7 , 4.85, 4.95, 4.7 , 4.95, 4.75, 4.7 , 5.7 ,
       4.9 , 4.  , 5.35, 5.  , 3.95])

----------------------------------------------------------------------------------------------------
PROBLEM 2
The mean final grade is 4.70. The standard deviation is 0.64.
----------------------------------------------------------------------------------------------------
PROBLEM 3
The percentage of students attenting less than 70% of classes is 15.0%.
----------------------------------------------------------------------------------------------------
PROBLEM 4
The average grade of those who attended at least 90% is 4.66.
----------------------------------------------------------------------------------------------------
PROBLEM 5
The average grade of those who attended less than 70% is 4.22.
----------------------------------------------------------------------------------------------------


## Random Numbers
---

NumPy also provides functions to generate random numbers. This is an important tool in applications of data science, e.g., in machine learning, we often need to generate random numbers to train our models although this is something we don't think about much&hellip; this will be a very important topic in the bootcamp!

You might be wondering how a computer can generate random numbers given that it is a purely deterministic machinery. This is a bit of a complex topic that we don't need to worry too much about, but we may want to keep in mind that we are dealing with so-called *pseudorandom numbers*. For most practical purposes, they behave just like truly random numbers, with the distinction that we may be able to reproduce them (which is also very useful in applications of data science).

Let's look at some examples.

In [ ]:
# We can generate a random number uniformly distributed between 0 and 1
np.random.rand()

In [ ]:
# ... or we may generate many of them at once
np.random.rand(5)

In [ ]:
# ... even in matrix form
np.random.rand(3, 3)

⚠️ Notice how we used `np.zeros((3, 3))` before while we just used `np.random.rand(3, 3)` now to create $3\times 3$ matrices in both cases. This is somewhat nonintuitive at first, but you should get used to these things as time passes by.

If you are unsure of how to pass the arguments to a function, make sure you look up the documentation!

In [ ]:
# Look up the documentation of np.zeros
np.zeros?

In [ ]:
np.random.rand?

Back to our random numbers, we can also easily sample from the standard normal distribution.

In [ ]:
# Sample 10 numbers from the standard normal distribution
np.random.randn(10)

Uniform and standard normal distributions are the bread and butter of data science. As such, they come up more often than other, which is why they have their shorthands `np.random.rand` and `np.random.randn`.

However, we may also sample from other distributions, e.g., the Poisson distribution. NumPy also provides this functionality and the same for many other distributions.

In [ ]:
np.random.poisson(5, 10)

Wait a second&hellip; why does the above only provide 10 numbers and not a $5\times 10$ matrix?

This is because the first parameter, `5`, is the $\lambda$ parameter of the Poisson distribution. The second parameter, `10`, is the number of samples we want to draw.


In [ ]:
# The same as above but more explicitly
np.random.poisson(lam=5, size=10)

In [ ]:
# It is also easy to sample a matrix in this way
np.random.poisson(lam=5, size=(3, 3))

As stated before, the continuous uniform distribution on $[0, 1]$ and the standard normal distribution, i.e., $\mathcal{N}(0, 1)$, are so ubiquitous that they have their shorthands. But they also come in the same form as the poisson distribution with parameters that can be specified.

In [ ]:
# Sample 5 numbers from the uniform distribution on [1, 5]
np.random.uniform(low=1, high=5, size=5)

In [ ]:
# Sample a 3x3 matrix of standard normal random numbers
# Equivalent to np.random.randn(3, 3) but we could specify another mean (loc)
# and standard deviation (scale)
np.random.normal(loc=0, scale=1, size=(3, 3))

### Reproducibility
---
We have mentioned before that our numbers are not *truly* random. Arguably, this is not a big deal for most practical purposes and it is quite useful to ensure that our results are reproducible.

To ensure reproducibility, we can set a so-called *seed*, which is an integer that initializes the random number generator in a reproducible way.

In [ ]:
# Set the random seed to 72
np.random.seed(72)
# Generate 5 random numbers, note that your classmates will all get the same numbers!
np.random.rand(5)

In [ ]:
# But if we run the random number generator again, we get different numbers
np.random.rand(5)

In [ ]:
# Set the seed and draw again, notice how the numbers are the same as the first time
np.random.seed(72)
np.random.rand(5)

⚠️ You typically shouldn't set the seed multiple times in the same code. Normally, you wan't to set the seed once and then *the sequence of all randomly generated numbers from the same distribution will be the same*.

If you set the seed once and run through the whole code a single time, the results will always be the same. Be careful, however, when setting the seed, running through the code and running the same cell multiple times, this will *continue using up numbers from the sequence*.

E.g., the following behavior often occurs:

1. First cell, we set the seed.
2. Second cell, we draw 5 random numbers.
3. Third cell, we draw 5 random numbers.

If we run the second cell twice, the results in the third cell will be different than from what would have been the case had we run the second cell only once. This can be a bit tricky to debug and often goes under the radar. Feel free to try it out!

In [ ]:
# Notice how 3 draws of 1 number from the same distribution are the same 
# as the first 3 numbers in our draw of 5 numbers above
np.random.seed(72)
np.random.rand(1), np.random.rand(1), np.random.rand(1)

### 🙀 🤯 Monte Carlo Experiments (Advanced)
---
A good way to get a feeling for the power of random number generators is to run [Monte Carlo experiments](https://en.wikipedia.org/wiki/Monte_Carlo_method). The topic is too large to really be covered in depth in this course, but it would be criminal to learn about computational randomness without at least mentioning it.

In fact, some of us use Monte Carlo experiments quite often the time to get a feeling for the behavior of a certain system or to verify that an analytical solution to a certain problem is correct.

The main idea is to simulate a random experiment many times and observe the behavior of the results. This will give us an empirical understanding of the problem we are dealing with.

#### Estimating Expected Values

Suppose we have three random variables $X$ and $Y$ are both standard normal random variables. $Z$, however, is defined as $$Z = \begin{cases} Y &\text{ if } X \geq 0\\ |Y| &\text{ otherwise} \end{cases}$$

Suppose that we are interested in finding the expected value $\mathbb{E}[XZ]$. Since $Z$ depends on $X$, we cannot use independence as $\mathbb{E}[XZ] \neq \mathbb{E}[X]\mathbb{E}[Z]$.

We can, however, use our newly acquired skills to get a good empirical estimate for this value using a Monte Carlo experiment.

In [56]:
# We will draw 1'000'000 samples, the more the better our approximation will be
n_samples = 1_000_000

# Draw X and Y
X = np.random.randn(n_samples)
Y = np.random.randn(n_samples)

# Compute Z
Z = np.where(X >= 0, Y, np.abs(Y))

# Compute the expected value
np.mean(X * Z)

-0.32111405869833787

This would have been much harder to solve analytically and using a few lines of code, we can already get a very good approximation $\mathbb{E}[XZ]\approx - 0.318$.

#### The Birthday Paradox

It is a well-known result that in a room of 23 people, there is a 50% chance that at least two people share the same birthday. This is something that one can solve analytically without too much effort, but sometimes, we just want to *see it for ourselves*.

So let's go ahead and simulate the birthday paradox step by step.

First, we can draw random birthdays (1 - 365, or rather 0 - 364) using the `np.random.randint` function.

In [57]:
# Number of people
n_people = 23 

# A word of caution, the upper bound is exclusive! 
# I.e., we draw 23 random integers from [0, 365), not [0, 365]
birthdays = np.random.randint(0, 365, n_people)
birthdays

array([ 38,  50, 197,  74, 204, 241,  26,  39, 250, 249, 199, 162,  14,
        58, 344, 194, 160,  75, 113, 239, 160, 223, 106])

Second, now that we have our birthdays, we would like to know if there are any duplicates, i.e., if there are two people with the same birthday.

NumPy provides a very convenient way to check for duplicates using the `np.unique` function. Note, that this function gives back the unique elements, and, if you pass `return_counts=True`, it will also give back the number of times each element occurs.

In [ ]:
# Notice that there are two outputs: the unique elements and the number of times they occur
np.unique(birthdays, return_counts=True)

In [ ]:
# We can store each of the returns into separate variables
unique_birthdays, counts = np.unique(birthdays, return_counts=True)

# counts now only contains the number of times each unique element occurs
counts

Lastly, we want to check whether there are any duplicates, i.e., if there is an element in `counts` that is greater than 1, which we can do using a reduction function and logical comparison.

In [ ]:
# Gives an array of booleans, i.e., the comparison is applied element-wise
duplicates = counts > 1
duplicates

In [ ]:
# Finally, we can reduce the array to a single boolean value using the `any` function
np.any(duplicates)

All right, let's run this experiment 1000 times and see how often we get a duplicate birthdate!

In [ ]:
# Set a seed for reproducibility
np.random.seed(72)

# Initialize the number of runs
n_runs = 1_000

# Initialize the array that will store whether there are duplicates in each run
has_duplicates = np.zeros(n_runs, dtype=bool)

# Loop over all runs
for i in range(n_runs):
    # Draw birthdays
    birthdays = np.random.randint(0, 365, n_people)

    # Check for duplicates
    unique_birthdays, counts = np.unique(birthdays, return_counts=True)
    has_duplicates[i] = np.any(counts > 1)

# Compute the percentage of runs that have duplicates
percentage_duplicates = np.mean(has_duplicates)
percentage_duplicates

Indeed, we find that in 53.3% of the runs, there are people with the same birthday! Increasing the number of runs will only make this result converge to its true value, try setting `n_runs` to 100 or 10'000 to see how the results differ.